In [2]:
import torch

In [3]:
tensor_a = torch.tensor([[10, 20], [30, 40]])
tensor_b = torch.tensor([[50, 20], [40, 60]])

## dim 이란?
dim은 PyTorch 텐서에서 특정 축(axis)을 따라 연산을 수행할지를 결정하는 매개변수입니다.

### dim=0 (행 기준 연산, 열 별 최댓값/최솟값)
각 열(column)마다 최대/최소 값을 찾습니다.  
즉, 세로 방향(axis=0)으로 연산하여 행(row)을 축소합니다.  
반환값:  
.values: 최댓값/최솟값 텐서  
.indices: 해당 최댓값/최솟값이 위치한 인덱스  

## tensor.argmax()
- argmax: 텐서의 최대값이 있는 인덱스를 반환합니다.
- argmin: 텐서의 최소값이 있는 인덱스를 반환합니다.


In [4]:
print(tensor_a)
print("shape :", tensor_a.shape)
print("dimention 지정 안했을때 max : ", torch.max(tensor_a))
print("dim = 0 일때 max : ", torch.max(tensor_a, dim=0).values)
print("dim = 1 일때 max : ", torch.max(tensor_a, dim=1).values)

print("dimention 지정 안했을때 min : ", torch.min(tensor_a))
print("dim = 0 일때 min : ", torch.min(tensor_a, dim=0).values)
print("dim = 1 일때 min : ", torch.min(tensor_a, dim=1).values)

tensor([[10, 20],
        [30, 40]])
shape : torch.Size([2, 2])
dimention 지정 안했을때 max :  tensor(40)
dim = 0 일때 max :  tensor([30, 40])
dim = 1 일때 max :  tensor([20, 40])
dimention 지정 안했을때 min :  tensor(10)
dim = 0 일때 min :  tensor([10, 20])
dim = 1 일때 min :  tensor([10, 30])


In [5]:
print(tensor_b)
print("shape :", tensor_b.shape)
print("dimention 지정 안했을때 max : ", torch.max(tensor_b))
print("dim = 0 일때 max :  ", torch.max(tensor_b, dim=0).values)
print("dim = 1 일때 max : ", torch.max(tensor_b, dim=1).values)

print("dimention 지정 안했을때 min : ", torch.min(tensor_b))
print("dim = 0 일때 min : ", torch.min(tensor_b, dim=0).values)
print("dim = 1 일때 min : ", torch.min(tensor_b, dim=1).values)

tensor([[50, 20],
        [40, 60]])
shape : torch.Size([2, 2])
dimention 지정 안했을때 max :  tensor(60)
dim = 0 일때 max :   tensor([50, 60])
dim = 1 일때 max :  tensor([50, 60])
dimention 지정 안했을때 min :  tensor(20)
dim = 0 일때 min :  tensor([40, 20])
dim = 1 일때 min :  tensor([20, 40])


In [6]:
# 4차원 텐서 (batch=2, channels=2, height=3, width=3)
tensor_c = torch.tensor(
    [
        [  # 첫 번째 배치 (batch=0)
            [  # 첫 번째 채널 (channel=0)
                [1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]
            ],
            [  # 두 번째 채널 (channel=1)
                [21, 22, 23, 24, 25],
                [26, 27, 28, 29, 30],
                [31, 32, 33, 34, 35],
                [36, 37, 38, 39, 40]
            ],
            [  # 세 번째 채널 (channel=2)
                [41, 42, 43, 44, 45],
                [46, 47, 48, 49, 50],
                [51, 52, 53, 54, 55],
                [56, 57, 58, 59, 60]
            ]
        ],
        [  # 두 번째 배치 (batch=1)
            [  # 첫 번째 채널 (channel=0)
                [61, 62, 63, 64, 65],
                [66, 67, 68, 69, 70],
                [71, 72, 73, 74, 75],
                [76, 77, 78, 79, 80]
            ],
            [  # 두 번째 채널 (channel=1)
                [81, 82, 83, 84, 85],
                [86, 87, 88, 89, 90],
                [91, 92, 93, 94, 95],
                [96, 97, 98, 99, 100]
            ],
            [  # 세 번째 채널 (channel=2)
                [101, 102, 103, 104, 105],
                [106, 107, 108, 109, 110],
                [111, 112, 113, 114, 115],
                [116, 117, 118, 119, 120]
            ]
        ]
    ]
)

max_values0 = torch.max(tensor_c, dim=0).values  # height(4) 방향으로 최대값 계산
max_values1 = torch.max(tensor_c, dim=1).values  # height(4) 방향으로 최대값 계산
max_values2 = torch.max(tensor_c, dim=2).values  # height(4) 방향으로 최대값 계산
max_values3 = torch.max(tensor_c, dim=3).values  # height(4) 방향으로 최대값 계산
print("max_values0 : ", max_values0.shape)  # torch.Size([3, 4, 5])
print(max_values0)
print("---------------------")
print("max_values1 : ", max_values1.shape)  # torch.Size([2, 4, 5])
print(max_values1)
print("---------------------")
print("max_values2 : ", max_values2.shape)  # torch.Size([2, 3, 5])
print(max_values2)
print("---------------------")
print("max_values3 : ", max_values3.shape)  # torch.Size([2, 3, 4])
print(max_values3)


max_values0 :  torch.Size([3, 4, 5])
tensor([[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]])
---------------------
max_values1 :  torch.Size([2, 4, 5])
tensor([[[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]])
---------------------
max_values2 :  torch.Size([2, 3, 5])
tensor([[[ 16,  17,  18,  19,  20],
         [ 36,  37,  38,  39,  40],
         [ 56,  57,  58,  59,  60]],

     

### dim 쉽게 기억하는 방법
- dim=N에서 N번째 축을 없애는 방향으로 연산  

In [7]:
# 3x3 Tensor 생성
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# 전체 합계
print(torch.sum(tensor))  # 45

# 열을 기준으로 합계 (dim=0) → 세로 방향 합
print(torch.sum(tensor, dim=0))  # tensor([12, 15, 18])

# 행을 기준으로 합계 (dim=1) → 가로 방향 합
print(torch.sum(tensor, dim=1))  # tensor([ 6, 15, 24])

# 최대값 구하기
print(torch.max(tensor, dim=1))  # (tensor([3, 6, 9]), tensor([2, 2, 2]))  (값, 인덱스)

tensor(45)
tensor([12, 15, 18])
tensor([ 6, 15, 24])
torch.return_types.max(
values=tensor([3, 6, 9]),
indices=tensor([2, 2, 2]))


## 행렬 및 벡터 계산
- dot: 내적
    - torch.dot(a,b)
    - a.dot(b) 

In [8]:
v1 = torch.tensor([1, 2])
u1 = torch.tensor([3, 4])

print(torch.dot(v1, u1))  # 1*3 + 2*4 = 11
print(v1.dot(u1))  # 1*3 + 2*4 = 11

tensor(11)
tensor(11)


### matmul: 행렬곱
- torch.matmul(a,b)
- a.matmul(b)

In [9]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

print(torch.matmul(A, B))
print(A.matmul(B))

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


## Broadcasting

- 브로드캐스팅은 텐서의 모양을 동적으로 확장하여 연산을 수행하는 기능입니다.
- scalar: 값으로 텐서 원소 변경하기
    - indexing으로 텐서 원소에 접근후 scalar 값으로 원소 변경  

In [10]:
tensor_a = torch.rand(3, 2)
print(tensor_a)

tensor_a[0, :] = 10
print(tensor_a)

tensor([[0.1654, 0.1054],
        [0.6577, 0.8478],
        [0.6862, 0.1412]])
tensor([[10.0000, 10.0000],
        [ 0.6577,  0.8478],
        [ 0.6862,  0.1412]])


텐서 값으로 텐서 원소 변경

In [11]:
tensor_a = torch.rand(3, 2)
print(tensor_a)

tensor_a[:, :] = torch.tensor([0, 1])
print(tensor_a)

tensor([[0.9226, 0.7750],
        [0.7868, 0.6160],
        [0.5964, 0.6026]])
tensor([[0., 1.],
        [0., 1.],
        [0., 1.]])


차원이 다른 텐서 간의 계산을 Broadcasting을 통해 수행

In [12]:
tensor_a = torch.eye(3)
print(tensor_a)

tensor_b = torch.tensor([1, 2, 3])
print(tensor_b)

print("A+B : ", tensor_a + tensor_b)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([1, 2, 3])
A+B :  tensor([[2., 2., 3.],
        [1., 3., 3.],
        [1., 2., 4.]])


In [13]:
tensor_a = torch.eye(3)
print(tensor_a)
tensor_b = torch.tensor([1, 2, 3]).reshape(3, 1)
print(tensor_b)

print("A+B : ", tensor_a + tensor_b)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1],
        [2],
        [3]])
A+B :  tensor([[2., 1., 1.],
        [2., 3., 2.],
        [3., 3., 4.]])


### unsqueeze 사용

In [14]:
# 1D 텐서 생성
tensor = torch.tensor([1, 2, 3])
print("Original Tensor:", tensor.shape)  # (3,)
print("Original Tensor:", tensor)  # (3,)

# 차원 추가: 첫 번째 차원(0번)에 추가
tensor_unsqueezed = torch.unsqueeze(tensor, dim=0)
print("Unsqueezed Tensor (dim=0):", tensor_unsqueezed.shape)  # (1, 3)
print("Unsqueezed Tensor (dim=0):", tensor_unsqueezed)  # (1, 3)

# 차원 추가: 두 번째 차원(1번)에 추가
tensor_unsqueezed_1 = torch.unsqueeze(tensor, dim=1)
print("Unsqueezed Tensor (dim=1):", tensor_unsqueezed_1.shape)  # (3, 1)
print("Unsqueezed Tensor (dim=1):", tensor_unsqueezed_1)  # (3, 1)


Original Tensor: torch.Size([3])
Original Tensor: tensor([1, 2, 3])
Unsqueezed Tensor (dim=0): torch.Size([1, 3])
Unsqueezed Tensor (dim=0): tensor([[1, 2, 3]])
Unsqueezed Tensor (dim=1): torch.Size([3, 1])
Unsqueezed Tensor (dim=1): tensor([[1],
        [2],
        [3]])


### COO Sparse Tensor 

#### COO 형식의 개념
- 좌표(indices): 값이 있는 요소의 위치를 나타냅니다.  
- 값(values): 실제 값들을 저장합니다.  
- 크기(size): 전체 텐서의 크기 (생략 가능).

In [15]:
# 좌표 (indices)
indices = torch.tensor([[0, 1, 1],  # row indices
                        [2, 0, 2]])  # col indices

# 값 (values)
values = torch.tensor([3, 4, 5])  # 해당 위치의 값

# 크기 지정 (3x3 행렬)
size = (3, 3)

# 희소 텐서 생성
sparse_tensor = torch.sparse_coo_tensor(indices, values, size)

# 출력
print("희소 텐서:")
print(sparse_tensor)

# 밀집(dense) 텐서로 변환
dense_tensor = sparse_tensor.to_dense()
print("\nDense 텐서:")
print(dense_tensor)

희소 텐서:
tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3, 4, 5]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)

Dense 텐서:
tensor([[0, 0, 3],
        [4, 0, 5],
        [0, 0, 0]])


COO 단점
- 중복 저장
- 특정 원소에 반복접근시 비효율적으로 접근

### CSR/CSC Sparse Tensor
- CSR: Compressed Sparse Row
- CSC: Compressed Sparse Column

In [16]:
t = torch.tensor([[0, 0, 3, 0, 4],
                  [0, 0, 5, 6, 0],
                  [7, 8, 0, 0, 0]])

print(t)
# CSR 형식으로 변환
print(t.to_sparse_csr())

# CSC 형식으로 변환
print(t.to_sparse_csc())

tensor([[0, 0, 3, 0, 4],
        [0, 0, 5, 6, 0],
        [7, 8, 0, 0, 0]])
tensor(crow_indices=tensor([0, 2, 4, 6]),
       col_indices=tensor([2, 4, 2, 3, 0, 1]),
       values=tensor([3, 4, 5, 6, 7, 8]), size=(3, 5), nnz=6,
       layout=torch.sparse_csr)
tensor(ccol_indices=tensor([0, 1, 2, 4, 5, 6]),
       row_indices=tensor([2, 2, 0, 1, 1, 0]),
       values=tensor([7, 8, 3, 5, 6, 4]), size=(3, 5), nnz=6,
       layout=torch.sparse_csc)


/var/folders/zw/_n2013wn763fp6tt7wpy6xdw0000gn/T/ipykernel_46829/3614091314.py:7: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/SparseCsrTensorImpl.cpp:55.)
  print(t.to_sparse_csr())


### Sparse CSC Tensor

In [17]:
ccol_indices = torch.tensor([0, 2, 2])  # 0이 아닌 열의 위치(첫번째는 무조건 0), 즉 column_pointer
row_indices = torch.tensor([0, 1])  # 0이 아닌 값의 행 위치
values = torch.tensor([1, 2])  # 0이 아닌 값

csc = torch.sparse_csc_tensor(ccol_indices=ccol_indices, row_indices=row_indices, values=values, size=(3, 2))

print(csc)
print(csc.to_dense())

tensor(ccol_indices=tensor([0, 2, 2]),
       row_indices=tensor([0, 1]),
       values=tensor([1, 2]), size=(3, 2), nnz=2, layout=torch.sparse_csc)
tensor([[1, 0],
        [2, 0],
        [0, 0]])


### Sparse Tensor 필요성
- 메모리 절약
- 연산 속도 향상
- 아주 큰 크기의 matrix 를 구성할때 일반적인 dense tensor 는 메모리 아웃 현상이 발생하지만, sparse tensor 는 메모리 아웃현상이 발생하지 않습니다.
    - to_dense(): sparse tensor 를 dense tensor 로 변환  

In [18]:
i = torch.randint(0, 100000, (200000,)).reshape(2, -1)
v = torch.rand(100000)
coo_sparse_tensor = torch.sparse_coo_tensor(indices=i, values=v, size=(100000, 100000))

In [19]:
crow = torch.randint(0, 100000, (100000,))
col = torch.randint(0, 100000, (100000,))
v = torch.rand(100000)
csr_sparse_tensor = torch.sparse_csr_tensor(crow_indices=crow, col_indices=col, values=v)

In [20]:
# coo_sparse_tensor.to_dense() # error

# sparse tensor 곱 , 덧셈, 행렬곱

In [25]:
# 좌표 (indices)
indices = torch.tensor([[0, 1, 1], [2, 0, 2]])  # 위치

# 값 (values)
values1 = torch.tensor([3, 4, 5])
values2 = torch.tensor([1, 2, 3])

# 크기
size = (3, 3)

# 두 개의 sparse 텐서 생성
sparse_tensor1 = torch.sparse_coo_tensor(indices, values1, size)
sparse_tensor2 = torch.sparse_coo_tensor(indices, values2, size)

# sparse 텐서 덧셈
sparse_add = sparse_tensor1 + sparse_tensor2

# 출력
print("희소 텐서 덧셈 결과:")
print(sparse_add)
print("\nDense 변환:")
print(sparse_add.to_dense())  # 밀집 텐서 변환

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3, 4, 5]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)
희소 텐서 덧셈 결과:
tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([4, 6, 8]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)

Dense 변환:
tensor([[0, 0, 4],
        [6, 0, 8],
        [0, 0, 0]])


In [23]:
# sparse 텐서 간 원소 곱 (Element-wise Multiplication)
sparse_mul = sparse_tensor1.mul(sparse_tensor2)

# 출력
print("\n희소 텐서 원소 곱 결과:")
print(sparse_mul)
print("\nDense 변환:")
print(sparse_mul.to_dense())  # 밀집 변환




희소 텐서 원소 곱 결과:
tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([ 3,  8, 15]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)

Dense 변환:
tensor([[ 0,  0,  3],
        [ 8,  0, 15],
        [ 0,  0,  0]])


In [24]:
# 밀집 행렬(Dense Tensor)
dense_matrix = torch.tensor([[1, 2, 3],
                             [4, 5, 6],
                             [7, 8, 9]])

# sparse 텐서와 dense 텐서 간 행렬곱
sparse_mm = torch.sparse.mm(sparse_tensor1, dense_matrix)

# 출력
print("\n희소 텐서 행렬곱 결과:")
print(sparse_mm)

# 3차원 sparse tensor 행렬곱 불가능!
# 2차원까지만 행렬곱 가증



희소 텐서 행렬곱 결과:
tensor([[21, 24, 27],
        [39, 48, 57],
        [ 0,  0,  0]])


### Sparse Tensor 요소 분석
```python
tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([4, 6, 8]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)
```

1. indices (좌표 인덱스) 
```python
tensor([[0, 1, 1],
        [2, 0, 2]])
```

2. values (값)
```python
tensor([4, 6, 8])
```

3. size (텐서 크기)
```python
(3, 3)
```

4. nnz (0이 아닌 값의 개수). 
3


### sparse tensor 의 indexing

- 일반 텐서와 동일하게 indexing 이 가능
    - slicing(":"을 사용)은 불가능 


In [26]:
a = torch.tensor([[0,1 ], [0, 2]], dtype=torch.float)
b = torch.tensor([[[1,0], [0,0]], [[1,0], [0,0]]], dtype=torch.float)

sparse_a = a.to_sparse()
sparse_b = b.to_sparse()

print("2차원 sparse tensor indexing")
print(a[0] == sparse_a[0].to_dense())

print("3차원 sparse tensor indexing")
print(b[0] == sparse_b[0].to_dense())

2차원 sparse tensor indexing
tensor([True, True])
3차원 sparse tensor indexing
tensor([[True, True],
        [True, True]])
